### ISSUE TITLE
Potential move to @sphinx-doc

### ISSUE THREAD

**Issue by AA-Turner** [ammaraskar/sphinx-problem-matcher#1]
Hi @ammaraskar,

Would you consider moving this repo to @sphinx-doc, for much the same rationale as https://github.com/ammaraskar/sphinx-action/issues/55?

If not, no worries, but I thought worth asking!

Thanks,
Adam

**Comment by ammaraskar** [comment]
Heya, more than happy to for this repo.

Let me think about the sphinx-action repo for a bit though, that one pretty much needs a rewrite because it's tied heavily to the sphinx version with no easy way to change it. It may be better to start from scratch for that one.

**Comment by AA-Turner** [comment]
Fab, thank you! According to [the docs](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository), transferring needs admin access in the transferee repo & ability to create repos in the destination -- I could temporarily add you as a member of the Sphinx-Doc organisation, would that work for you?

> Let me think about the sphinx-action repo for a bit though ... it may be better to start from scratch for that one.

OK, I'll hold off for a while---feel free to ping me for input at any point if useful.

A

**Comment by ammaraskar** [comment]
> I could temporarily add you as a member of the Sphinx-Doc organisation, would that work for you?

Sure, let me know when you've added me and I'll ping you after it's transferred

**Comment by AA-Turner** [comment]
Done

**Comment by ammaraskar** [comment]
Moved over https://github.com/sphinx-doc/sphinx-problem-matcher :) Feel free to remove me now

**Comment by AA-Turner** [comment]
Do you still want permissions on this repo? If so I can make you a "collaborator" rather than removing you.

A

**Comment by ammaraskar** [comment]
Sure, that sounds good.

**Comment by AA-Turner** [comment]
Another Q (sorry!): Would you be willing to relicence to BSD-2-Clause (as used by Sphinx) or "Apache or MIT" (as used by e.g. Rust)?

A

**Comment by ammaraskar** [comment]
Sure, I'll relicense to BSD-2-Clause.
